booking_buddy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("customers/", include(("customers.urls", "customers"), namespace="customers")),
    path("schedules/", include(("schedules.urls", "schedules"), namespace="schedules")),
    path("", include(("landing.urls", "landing"), namespace="landing")),
]

customers/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("detail/<customer_id>/", views.detail, name="detail"),
]

landing/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

customers/models.py
from django.db import models
from django.http import HttpResponse

# Create your models here.


def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")


class Customer(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    cell = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return f"{self.first_name}, {self.last_name}"

customers/views.py
from datetime import datetime

from django.http import HttpResponse
from django.shortcuts import render

from customers.models import Customer
from schedules.models import Schedules


def index(request):
    customers = []
    for customer in Customer.objects.all():
        result = {
            "first_name": customer.first_name,
            "last_name": customer.last_name,
            "cell": customer.cell,
            "email": customer.email,
            "number_of_appointments": 0,
        }
        result["number_of_appointments"] = Schedules.objects.filter(
            Customer=customer
        ).count()

        result["next_appointment"] = (
            Schedules.objects.filter(Customer=customer, StartTime__gt=datetime.now())
            .order_by("StartTime")
            .first()
        )

        customers.append(result)
    context = {"customers": customers}
    return render(request, "customers/index.html", context)


def about(request):
    return HttpResponse("Hello to the about page")


def detail(request, customer_id):
    return HttpResponse(f"hello, customer with id: {customer_id}")

customers/templates/customers/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <link
      rel="icon"
      type="image/x-icon"
      href="https://cdn0.iconfinder.com/data/icons/pinpoint-interface/48/reservations_copy-256.png"
    />
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Customers</title>
    <!-- Tailwind -->
    <link
      href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css"
      rel="stylesheet"
    />
    <style>
      @import url("https://fonts.googleapis.com/css?family=Karla:400,700&display=swap");
      .font-family-karla {
        font-family: karla;
      }

      .bg-sidebar {
        background: #ffa500;
      }

      .active-nav-link {
        background: #d48a00;
      }

      .nav-item:hover {
        background: #b07608;
      }
    </style>
  </head>
  <body class="bg-gray-100 font-family-karla flex">
    <aside
      class="relative bg-sidebar min-h-screen w-64 hidden sm:block shadow-xl"
    >
      <div class="p-6">
        <a
          href='{% url "landing:index" %}'
          class="text-white text-3xl font-semibold uppercase hover:text-gray-300"
        >
          Booking Buddy
        </a>
      </div>
      <nav class="text-white text-base font-semibold pt-3">
        <a
          href='{% url "schedules:index" %}'
          class="flex items-center active-nav-link text-white py-4 pl-6 nav-item"
        >
          <i class="fas fa-calendar-alt mr-3"></i>
          Schedules
        </a>
        <a
          href='{% url "customers:index" %}'
          class="flex items-center active-nav-link text-white py-4 pl-6 nav-item"
        >
          <i class="fas fa-user-alt mr-3"></i>
          Customers
        </a>
        <a
          href='{% url "admin:index" %}'
          class="flex items-center active-nav-link text-white py-4 pl-6 nav-item"
        >
          <i class="fas fa-plus mr-3"></i>
          Admin
        </a>
      </nav>
    </aside>
    <div
      class="w-full l-full overflow-x-hidden border-t flex flex-col divide-dashed"
    >
      {% block content %}{% endblock %}
    </div>
    <!-- Font Awesome -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"
      integrity="sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs="
      crossorigin="anonymous"
    ></script>
  </body>
</html>

customers/templates/customers/index.html
{% extends 'customers/base.html' %}

<!-- content -->
{% block content %}
<div class="bg-white min-h-screen overflow-auto divide divide-dashed">
  <table class="min-w-full bg-white">
    <thead class="bg-gray-800 text-white">
      <tr>
        <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">
          First name
        </th>
        <th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">
          Last name
        </th>
        <th class="text-left py-3 px-4 uppercase font-semibold text-sm">
          Phone
        </th>
        <th class="text-left py-3 px-4 uppercase font-semibold text-sm">
          Email
        </th>
        <th class="text-left py-3 px-4 uppercase font-semibold text-sm">
          Next Appointment
        </th>
      </tr>
    </thead>
    <tbody class="text-gray-700">
      {% for customer in customers %}
      <tr>
        <td class="w-1/3 text-left py-3 px-4">{{customer.first_name}}</td>
        <td class="w-1/3 text-left py-3 px-4">{{customer.last_name}}</td>
        <td class="text-left py-3 px-4">
          <a class="hover:text-blue-500" href="tel:{{customer.cell}}">
            {{customer.cell}}
          </a>
        </td>
        <td class="text-left py-3 px-4">
          <a class="hover:text-blue-500" href="mailto:{{customer.email}}">
            {{customer.email}}
          </a>
        </td>
        <td class="w-1/3 text-left py-3 px-4">
          {{customer.next_appointment.StartTime}}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}