booking_buddy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("customers/", include(("customers.urls", "customers"), namespace="customers")),
    path("schedules/", include(("schedules.urls", "schedules"), namespace="schedules")),
    path("", include(("landing.urls", "landing"), namespace="landing")),
]

landing/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

schedules/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("calendar/<int:year>/<int:month>/", views.get_calendar, name="calendar"),
    path(
        "calendar/<int:year>/<int:month>/<int:day>",
        views.get_calendar,
        name="calendardaily",
    ),
    path(
        "make_appointment/",
        views.make_appointment,
        name="make_appointment",
    ),
]

schedules/models.py
from django.db import models
from datetime import datetime, timedelta
from customers.models import Customer

# Create your models here.
class Service(models.Model):
    Service = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    LengthInMinutes = models.IntegerField()
    Charge = models.FloatField()

    def __str__(self):
        return self.Service


class Schedules(models.Model):
    StartTime = models.DateTimeField(max_length=100)
    Customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    ServiceTable = models.ForeignKey(Service, on_delete=models.CASCADE, null=True)

    def __str__(self):
        result = ""
        if self.Customer:
            result += str(self.Customer)
        LengthInMinutes = 60
        if self.ServiceTable:
            LengthInMinutes = self.ServiceTable.LengthInMinutes
        EndTime = self.StartTime + timedelta(minutes=LengthInMinutes)
        result += (
            " "
            + datetime.strftime(self.StartTime, "%x")
            + ", "
            + datetime.strftime(self.StartTime, "%X")
            + " "
            + "  "
            + " to "
            + datetime.strftime(EndTime, "%X")
            + "   "
        )
        if self.ServiceTable:
            result += str(self.ServiceTable)
        return result

schedules/forms.py
from django import forms
from django.forms import ModelForm
from schedules.models import Schedules
from django import forms

time_choices = [(d, f"{str(d).zfill(2)}:00") for d in range(9, 21)]


class AppointmentForm(ModelForm):
    date = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "bg-gray-200 appearance-none border-2 border-gray-200 rounded-lg w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-500",
                "x-model": "event_date",
                "readonly": True,
            }
        )
    )
    time = forms.IntegerField(widget=forms.Select(choices=time_choices))

    class Meta:
        model = Schedules
        fields = ["Customer", "ServiceTable"]

schedules/views.py
import calendar
from datetime import datetime, timedelta

from django.http import HttpResponse
from django.shortcuts import redirect, render

from .forms import AppointmentForm
from .models import Schedules, Customer, Service


def index(request):
    now = datetime.now()
    return redirect("schedules:calendardaily", now.year, now.month, now.day)


def about(request):
    return HttpResponse("this is not done go away")


def get_calendar(request, year, month, day=None):
    if day:
        is_monthly = False
    else:
        is_monthly = True

    schedules = []
    kwargs = {
        "StartTime__year": year,
        "StartTime__month": month,
    }
    if day:
        kwargs["StartTime__day"] = day
    schedules = []
    for schedule in Schedules.objects.filter(**kwargs):

        result = {
            "StartTime": schedule.StartTime,
            "EndTime": schedule.StartTime
            + timedelta(minutes=schedule.ServiceTable.LengthInMinutes),
            "Customer": schedule.Customer,
            "ServiceTable": schedule.ServiceTable,
        }
        schedules.append(result)
    dates = []

    calendar.setfirstweekday(6)
    calen = calendar.month(year, month, w=2)
    lines = calen.strip().split("\n")[2:]
    calen = 0
    for line in lines:
        days = line.split()
        if calen == 0 and len(days) < 7:
            days = [None] * (7 - len(days)) + days
        dates.append(days)
        calen += 1

    next_year = year
    prev_year = year
    next_month = month + 1
    if next_month > 12:
        next_month = 1
        next_year = next_year + 1
    prev_month = month - 1
    if prev_month < 1:
        prev_month = 12
        prev_year = prev_year - 1

    month_num = month
    if month == 1:
        month = "January"
    elif month == 2:
        month = "Feburary"
    elif month == 3:
        month = "March"
    elif month == 4:
        month = "April"
    elif month == 5:
        month = "May"
    elif month == 6:
        month = "June"
    elif month == 7:
        month = "July"
    elif month == 8:
        month = "August"
    elif month == 9:
        month = "September"
    elif month == 10:
        month = "October"
    elif month == 11:
        month = "November"
    elif month == 12:
        month = "December"

    if is_monthly:
        if len(schedules) < 40:
            color = "green-50"
        elif len(schedules) < 75:
            color = "green-200"
        elif len(schedules) < 100:
            color = "green-400"
        elif len(schedules) < 150:
            color = "yellow-300"
        elif len(schedules) < 200:
            color = "yellow-600"
        elif len(schedules) < 240:
            color = "red-500"
        elif len(schedules) < 280:
            color = "red-800"
        elif len(schedules) < 300:
            color = "red-900"
        elif len(schedules) < 340:
            color = "pink-900"
        else:
            color = "purple-900"
    else:
        if len(schedules) < 2:
            color = "green-50"
        elif len(schedules) < 3:
            color = "green-200"
        elif len(schedules) < 5:
            color = "green-400"
        elif len(schedules) < 7:
            color = "yellow-300"
        elif len(schedules) < 9:
            color = "yellow-600"
        elif len(schedules) < 11:
            color = "red-500"
        elif len(schedules) < 14:
            color = "red-800"
        elif len(schedules) < 17:
            color = "red-900"
        elif len(schedules) < 20:
            color = "pink-900"
        elif len(schedules) < 25:
            color = "purple-900"
        else:
            color = "gray-900"

    context = {
        "schedules": schedules,
        "dates": dates,
        "month": month,
        "year": year,
        "day": str(day) if day else None,
        "is_monthly": is_monthly,
        "month_num": month_num,
        "next_month": next_month,
        "prev_month": prev_month,
        "next_year": next_year,
        "prev_year": prev_year,
        "color": color,
    }

    return render(request, "schedules/index.html", context)


def make_appointment(request):

    if request.method == "POST":
        appointment_datetime = datetime.strptime(
            request.POST.get("date"), "%a %b %d %Y"
        )
        appointment_datetime = appointment_datetime.replace(
            hour=int(request.POST.get("time"))
        )
        customer = Customer.objects.get(id=request.POST.get("Customer"))
        service = Service.objects.get(id=request.POST.get("ServiceTable"))

        schedule = Schedules(
            StartTime=appointment_datetime,
            Customer=customer,
            ServiceTable=service,
        )
        schedule.save()

        now = datetime.now()
        return redirect("schedules:calendardaily", now.year, now.month, now.day)

    form = AppointmentForm()
    context = {"form": form}
    return render(request, "schedules/appointment.html", context)

schedules/templates/schedules/index.html
{% extends 'customers/base.html' %}

<!-- content -->
{% block content %}
<div class="bg-white min-h-screen overflow-auto">
  <div class="flex items-center justify-center py-8">
    <div class="max-w-lg w-full shadow-lg">
      <div class="md:p-8 p-5 dark:bg-blue-100 bg-white rounded-lg">
        <div class="px-4 flex items-center justify-between">
          <span
            tabindex="0"
            class="focus:outline-none text-base font-bold dark:text-gray-100 text-gray-800"
          >
            <a href='{% url "schedules:calendar" year month_num%}'>
              {{month}} {%if day%}{{day}} {%endif%}, {{year}}
            </a>
          </span>
          <div class="flex items-center">
            <a
              aria-label="calendar backward"
              class="focus:text-gray-400 hover:text-gray-400 text-gray-800 dark:text-gray-100"
              href='{% url "schedules:calendar" prev_year prev_month %}'
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="icon icon-tabler icon-tabler-chevron-left"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                stroke-width="1.5"
                stroke="currentColor"
                fill="none"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <polyline points="15 6 9 12 15 18" />
              </svg>
            </a>
            <a
              aria-label="calendar forward"
              class="focus:text-gray-400 hover:text-gray-400 ml-3 text-gray-800 dark:text-gray-100"
              href='{% url "schedules:calendar" next_year next_month %}'
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="icon icon-tabler icon-tabler-chevron-right"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                stroke-width="1.5"
                stroke="currentColor"
                fill="none"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <polyline points="9 6 15 12 9 18" />
              </svg>
            </a>
          </div>
        </div>
        <div class="flex items-center justify-between pt-12 overflow-x-auto">
          <table class="w-full">
            <thead>
              <tr>
                <th>
                  <div class="w-full flex justify-center">
                    <p
                      class="text-base font-medium text-center text-gray-800 dark:text-gray-100"
                    >
                      Mo
                    </p>
                  </div>
                </th>
                <th>
                  <div class="w-full flex justify-center">
                    <p
                      class="text-base font-medium text-center text-gray-800 dark:text-gray-100"
                    >
                      Tu
                    </p>
                  </div>
                </th>
                <th>
                  <div class="w-full flex justify-center">
                    <p
                      class="text-base font-medium text-center text-gray-800 dark:text-gray-100"
                    >
                      We
                    </p>
                  </div>
                </th>
                <th>
                  <div class="w-full flex justify-center">
                    <p
                      class="text-base font-medium text-center text-gray-800 dark:text-gray-100"
                    >
                      Th
                    </p>
                  </div>
                </th>
                <th>
                  <div class="w-full flex justify-center">
                    <p
                      class="text-base font-medium text-center text-gray-800 dark:text-gray-100"
                    >
                      Fr
                    </p>
                  </div>
                </th>
                <th>
                  <div class="w-full flex justify-center">
                    <p
                      class="text-base font-medium text-center text-gray-800 dark:text-gray-100"
                    >
                      Sa
                    </p>
                  </div>
                </th>
                <th>
                  <div class="w-full flex justify-center">
                    <p
                      class="text-base font-medium text-center text-gray-800 dark:text-gray-100"
                    >
                      Su
                    </p>
                  </div>
                </th>
              </tr>
            </thead>
            <tbody>
              {% for week in dates %}
              <tr>
                {% for aday in week %}
                <td class="pt-6">
                  <div
                    class="px-2 py-2 cursor-pointer flex w-full justify-center"
                  >
                    {% if aday %}
                    <a
                      class="{%if day == aday%} bg-indigo-200 text-gray-900 text-lg rounded-3xl px-3 py-1 active-nav-link{%else%} {%endif%}"
                      href='{% url "schedules:calendardaily" year month_num aday %}'
                      >{{aday}}</a
                    >
                    {% endif %}
                  </div>
                </td>
                {% endfor %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="sm:px-6 max-w-5xl w-full">
    <div class="px-4 md:px-10 py-4 w-full md:py-7">
      <div class="flex items-center justify-between">
        <a
          href='{% url "schedules:make_appointment" %}'
          class="focus:ring-2 focus:ring-offset-2 text-lg rounded-3xl leading-none text-blue-100 py-7 px-7 bg-blue-300 rounded hover:bg-blue-400 focus:outline-none"
        >
          Add Schedules
        </a>
        <a
          class="focus:ring-2 focus:ring-offset-2 text-lg rounded-3xl leading-none text-gray-700 py-7 px-7 bg-red-500 rounded hover:bg-red-400 focus:outline-none"
        >
          Delete Schedules
        </a>
        <p
          tabindex="0"
          class="focus:outline-none text-base sm:text-lg md:text-xl lg:text-2xl font-bold leading-normal text-gray-800 rounded-lg"
        >
          {%if is_monthly%} Monthly {%else%} Daily {%endif%}Appointments
          <span class="bg-{{color}} sm:text-2xl px-3 py-2 rounded-3xl"
            >{{schedules|length}}</span
          >
        </p>
      </div>
    </div>
    <div class="bg-white py-4 md:py-7 w-full px-4 md:px-8 xl:px-10 rounded-lg">
      <div class="sm:flex items-center justify-between">
        <div class="flex items-center">
          <a
            class="rounded-full focus:outline-none focus:ring-2 focus:bg-indigo-50 focus:ring-indigo-800"
            href="javascript:void(0)"
          >
          </a>
          <a
            class="rounded-full focus:outline-none focus:ring-2 focus:bg-indigo-50 focus:ring-indigo-800 ml-4 sm:ml-8"
            href="javascript:void(0)"
          >
          </a>
          <a
            class="rounded-full focus:outline-none focus:ring-2 focus:bg-indigo-50 focus:ring-indigo-800 ml-4 sm:ml-8"
            href="javascript:void(0)"
          >
          </a>
        </div>
      </div>
      <div class="mt-7 overflow-x-auto">
        <table class="w-full whitespace-nowrap">
          <tbody>
            {% for schedule in schedules %}
            <tr
              tabindex="0"
              class="focus:outline-none h-16 w-full border border-gray-100 rounded"
            >
              <td>
                <a
                  class="focus:ring-2 focus:ring-offset-2 text-sm leading-none text-blue-100 py-3 px-6 bg-blue-300 rounded hover:bg-blue-400 focus:outline-none active-nav-link nav-item"
                >
                  > Done
                </a>
                <div class="ml-5"></div>
              </td>
              <td class="">
                <div class="flex items-center pl-5">
                  <p
                    class="text-base font-small leading-none text-gray-700 mr-2"
                  >
                    {{ schedule.Customer.first_name }}
                  </p>
                  <p
                    class="text-base font-small leading-none text-gray-700 mr-2"
                  >
                    {{ schedule.Customer.last_name }}
                  </p>
                </div>
              </td>
              <td class="pl-3">
                <div class="flex items-center">
                  <p
                    class="text-base font-small leading-none text-gray-700 mr-2"
                  >
                    {{ schedule.StartTime }}
                  </p>
                </div>
              </td>
              <td class="pl-5">
                <div class="flex items-center">
                  <p class="text-sm leading-none text-gray-600 ml-2"></p>
                </div>
                <p class="text-base font-small leading-none text-gray-700 mr-2">
                  to
                </p>
              </td>
              <td class="pl-5">
                <div class="flex items-center">
                  <p class="text-sm leading-none text-gray-600 ml-2"></p>
                </div>
                <p class="text-base font-small leading-none text-gray-700 mr-2">
                  {{ schedule.EndTime }}
                </p>
              </td>
              <td class="pl-5">
                <div class="flex items-center">
                  <p
                    class="text-base font-small leading-none text-gray-700 mr-2"
                  >
                    {{ schedule.ServiceTable.type }}
                  </p>
                </div>
              </td>
              <td class="pl-5">
                <button
                  class="py-3 px-3 text-sm focus:outline-none leading-none text-blue-400 bg-red-blue-200 rounded"
                >
                  <p
                    class="text-base font-small leading-none text-gray-700 mr-2"
                  >
                    {{ schedule.ServiceTable.LengthInMinutes }}
                  </p>
                  <p
                    class="text-base font-small leading-none text-gray-700 mr-2"
                  >
                    min
                  </p>
                </button>
              </td>
              <td class="pl-4">
                <button
                  class="focus:ring-2 focus:ring-offset-2 focus:ring-green-300 text-sm leading-none text-gray-600 py-3 px-5 bg-gray-100 rounded hover:bg-gray-200 focus:outline-none"
                >
                  View
                </button>
              </td>
              <td>
                <div class="relative px-5 pt-2">
                  <button
                    class="focus:ring-2 rounded-md focus:outline-none"
                    onclick="dropdownFunction(this)"
                    role="button"
                    aria-label="option"
                  ></button>
                  <div
                    class="bg-white shadow w-24 absolute z-30 right-0 mr-6 hidden"
                  >
                    <div
                      tabindex="0"
                      class="focus:outline-none focus:text-indigo-600 text-xs w-full hover:bg-indigo-700 py-4 px-4 cursor-pointer hover:text-white"
                    >
                      <p>Edit</p>
                    </div>
                    <div
                      tabindex="0"
                      class="focus:outline-none focus:text-indigo-600 text-xs w-full hover:bg-indigo-700 py-4 px-4 cursor-pointer hover:text-white"
                    >
                      <p>Delete</p>
                    </div>
                  </div>
                </div>
              </td>
            </tr>
            <tr class="h-3"></tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}